### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by darkspacer** [cirebon-dev/notification_bot#1]
when starting the app.py I get an error:

> Traceback (most recent call last):                                                                File "/home/makito/notification_bot/app.py", line 26, in <module>
>     key = ENCRYPTION_KEY.encode()
> AttributeError: 'NoneType' object has no attribute 'encode'

how can I fix this?

**Comment by guangrei** [comment]
It seems you've fixed the problem, thanks for your interest in this project.

I have updated the code with file support, please take a look and feel free to give me a feedback.

Regards

**Comment by n0rthl1ght** [comment]
Hey! How i can fix this error?
